version: 0.1

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      npm install
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      npm run build
      # - command
  post_build:
    commands:
      cd $CODEBUILD_SRC_DIR/build; zip -r ../build.zip *
      # - command
artifacts:
  files:
     -  build.zip
    # - location
  #base-directory: 'build'
  discard-paths: yes